### ISSUE TITLE
IncrementalInference not installed after loading the notebook (2NonGaussianJuliaBinder)

### ISSUE THREAD

**Issue by dehann** [NavAbility/BinderNotebooks#13]
The first time I tried, IncrementalInference package was not installed after loading the notebook.  So i did this in a separate cell by hand:
```julia
import Pkg; Pkg.add(Pkg.PackageSpec(name="IncrementalInference", version="0.27"))
```

and now I'm not sure if we have to add that for all first time runs?

When I call up the notebook now, it seems to be running without having to install the package again.

**Comment by Affie** [comment]
I did all the package stuff in tut 1. So it was fixed with the merge.

**Comment by GearsAD** [comment]
It was included as part of the Project.toml, it looks like @Affie updated it to 0.27.1. Is this still an issue from a clean space?

https://github.com/NavAbility/BinderNotebooks/commit/703df6e75df450fd668eb888c6854eb1fc97fcbf#diff-6d1205e03b7a43c01ed2ac8b8c83eb58c6f3a3b1360769e18644245abee8c565L382-R456

**Comment by dehann** [comment]
https://github.com/NavAbility/BinderNotebooks/pull/16#issuecomment-1060023091
