### ISSUE TITLE
ICRA Tutorial 2, What to do about plotDFG

### ISSUE THREAD

**Issue by dehann** [NavAbility/BinderNotebooks#14]
How are we going to plot the graph topologies?    
- [x] ~~Perhaps we want to show this with NavAbility App instead?~~  
- [x] Tut2 content currently has `plotDFG` but that is missing a `using GraphPlot` call.
- [x] Another issue we need to add module namespace `DFG.plotDFG(fg)`
  - #16 
  - #9

**Comment by dehann** [comment]
![Screenshot from 2022-03-05 14-45-25](https://user-images.githubusercontent.com/6412556/156902195-ec951ffb-c355-4f2d-b595-04819297e87b.png)

----

![Screenshot from 2022-03-05 14-44-26](https://user-images.githubusercontent.com/6412556/156902158-0eec5451-1b71-42d9-abd2-a3a419353e7a.png)

**Comment by jim-hill-r** [comment]
I'd say use Caesar calls in the Caesar versions and app for the NavAbility versions.

**Comment by dehann** [comment]
That works for me
