### ISSUE TITLE
Julia-Caesar Tutorial 3: VSCode is failing on the logger setting.

### ISSUE THREAD

**Issue by GearsAD** [NavAbility/BinderNotebooks#28]
![image](https://user-images.githubusercontent.com/6854507/160046293-970e92eb-fe73-4f1f-aabe-ff4615db8126.png)

To reproduce:
- Try run tutorial 3's logger statement in VSCode:
```
using Logging
global_logger( SimpleLogger(Logging.Error) );
```

**Comment by dehann** [comment]
We can remove that if it's too much hassle.  Just to reduce the amount of printouts

**Comment by jim-hill-r** [comment]
Notebooks have a suppression feature out of the box I think. Not sure how to set it though.

**Comment by dehann** [comment]
Johan uses a different approach which might work better:
- https://github.com/NavAbility/BinderNotebooks/issues/35#issuecomment-1079638250
