### ISSUE TITLE
Rendered results not showing up in the quick read option option?

### ISSUE THREAD

**Issue by Affie** [NavAbility/BinderNotebooks#32]
It shows results here: https://github.com/NavAbility/BinderNotebooks/blob/main/julia/caesar-api/icra-1-simple.ipynb

**Comment by jim-hill-r** [comment]
Thanks for the report. I'll take a look this weekend.

**Comment by jim-hill-r** [comment]
Closed by #439

Everything but images. Specific issues can be opened for any missing cells.
