### ISSUE TITLE
Tutorial 1 Links in App Go to Old versions of notebooks

### ISSUE THREAD

**Issue by jim-hill-r** [NavAbility/BinderNotebooks#39]
![image](https://user-images.githubusercontent.com/25872250/160244817-2d37a04a-4a0e-40d5-b563-fe06f3c6d892.png)

**Comment by GearsAD** [comment]
Hmm, that's new. I'll look at it, thanks.

**Comment by jim-hill-r** [comment]
O this might be old. My links take me to old notebooks for some reason. Maybe solve the links being stable problem first as that might be root cause. Can't seem to find issue.

**Comment by dehann** [comment]
Hi, not sure exactly to what this issue is referring to -- just to let you know i have been fixing some issues  inside the SDK.py of Tut1, so just make sure you use the latest on main.

**Comment by jim-hill-r** [comment]
Changed title to represent real issue. App links get stale for some reason.
