### ISSUE TITLE
Tutorial 2: DFG.plotDFG(fg) failing

### ISSUE THREAD

**Issue by jim-hill-r** [NavAbility/BinderNotebooks#40]
DFG.plotDFG(fg) is failing when running Tutorial 2 Caesar version in Binder.

To reproduce: Go to the following link and run the tutorial from the top. Cell 6 is failing.

https://mybinder.org/v2/gh/NavAbility/BinderNotebooks/30173aa54f1d34be92ceed50f72601236949b294?urlpath=lab%2Ftree%2Fjulia%2Fcaesar-api%2Ficra-2-nongaussian.ipynb

**Comment by dehann** [comment]
Are you seeing this in your version?
![Screenshot from 2022-03-26 09-14-07](https://user-images.githubusercontent.com/6412556/160248101-f3494f23-455f-4313-9580-0842184c3428.png)

When I follow the link, I get an older version of the notebook that does not have the `using GraphPlot` line?

**Comment by dehann** [comment]
Yup, here is what I get when following the link (looks like an older version somehow):
![Screenshot from 2022-03-26 09-27-41](https://user-images.githubusercontent.com/6412556/160248580-b68ac4dd-cfb3-4585-a8af-650db233dafa.png)

**Comment by Affie** [comment]
I tested tut 2 and it looks to be working.

**Comment by jim-hill-r** [comment]
I think the links are versioned.. drat. Need to figure out how to link to a notebook from app.

**Comment by dehann** [comment]
Cool, we can leave the assignment to me until the versioning is done.  I'll prod again to check that this is tied down before show time.
