### ISSUE TITLE
Tutorial 1: Solving 1000 times (incorp as part of load test instead)

### ISSUE THREAD

**Issue by dehann** [NavAbility/BinderNotebooks#43]
Using the SDK, were able to do this more easily -- this code is not ready for prime time, since the API might be tweaked before ICRA for easier use, but here is the current best:

```julia

# 

using NavAbilitySDK
using Random
using LinearAlgebra
## convert this to SDK.jl and run

# Creating one client and two contexts

number = 1

apiUrl = "https://api.d1.navability.io"
userId = "Guest"
robotId = "MonteCarlo_100"
sessionId = "TestSession"
client = NavAbilityHttpsClient(apiUrl)

ids = 1:100
contexts = [Client(userId,robotId,sessionId*string(i)) for i in ids]
solveIds = []
for i in ids
  context = contexts[i]
  @info "Running context $(i)"
  variables = [
    Variable("x0", :Pose2),
    Variable("x1", :Pose2),
    Variable("x2", :Pose2),
    Variable("x3", :Pose2),
    Variable("x4", :Pose2),
    Variable("l1", :Point2)
  ]
  factors = [
    Factor("x0f1", "PriorPose2", ["x0"], 
      PriorPose2Data(
        Z=FullNormal(
          [0.0, 0.0, 0.0], 
          diagm([0.05, 0.05, 0.01].^2)))),
    Factor("x0x1f1", "Pose2Pose2", ["x0","x1"], 
      Pose2Pose2Data(
        Z=FullNormal(
          [1.0, 0.0, pi/2], 
          diagm([0.1, 0.1, 0.01].^2)))),
    Factor("x1x2f1", "Pose2Pose2", ["x1","x2"], 
      Pose2Pose2Data(
        Z=FullNormal(
          [1.0, 0.0, pi/2], 
          diagm([0.1, 0.1, 0.01].^2)))),
    Factor("x2x3f1", "Pose2Pose2", ["x2","x3"], 
      Pose2Pose2Data(
        Z=FullNormal(
          [1.0, 0.0, pi/2], 
          diagm([0.1, 0.1, 0.01].^2)))),
    Factor("x3x4f1", "Pose2Pose2", ["x3","x4"], 
      Pose2Pose2Data(
        Z=FullNormal(
          [1.0, 0.0, pi/2], 
          diagm([0.1, 0.1, 0.01].^2)))),
                  
    Factor("x0l1f1", "Pose2Point2BearingRange", ["x0","l1"], 
      Pose2Point2BearingRangeData(
        bearing = Normal(0, 0.03), 
        range = Normal(0.5, 0.1))),
    Factor("x4l1f1", "Pose2Point2BearingRange", ["x4","l1"], 
      Pose2Point2BearingRangeData(
        bearing = Normal(0, 0.03), 
        range = Normal(0.5, 0.1)))
  ]

  # Add the variables
  @info "$(i): Pushing variables..."
  resultIds = String[]
  for v in variables
    push!(resultIds, addVariable(client, context, v))
  end
  waitForCompletion(client, string.(resultIds); expectedStatuses=["Complete"])

  # Add the factors
  @info "$(i): Pushing factors..."
  resultIds = String[]
  for f in factors
    push!(resultIds, addFactor(client, context, f))
  end
  waitForCompletion(client, string.(resultIds); expectedStatuses=["Complete"])

  # Solve the session
  @info "$(i): Solving sessions..."
  resultId = solveSession(client, context)
  push!(solveIds, resultId)
  # resultId = solveSession(client, context)
  # push!(solveIds, resultId)

  sleep(60)
end

waitForCompletion(client, [resultId]; expectedStatuses=["Complete"])

# getStatusLatest(client, resultId)
# getStatusesLatest(client, [resultId])

# Get the PPEs 
variables = getVariables(client, context; detail=SUMMARY)
ppes = Dict([v["label"] for v in variables].=>[v["ppes"] for v in variables])

```

Thanks @GearsAD for the help!

**Comment by dehann** [comment]
HI @Affie , the MonteCarlo solves have worse numerical performance than Tutorial 1.  See the code above.  Here we upload the whole graph and solve once at the end.  The way tha tTut1 works, is we add a bit, solve, then add more and solve again.  That avoids the batch solve quirk of x4 being pulled aside.  PS second solve fixes that, but we should still debug that in IIF when we get a change to do so.

**Comment by dehann** [comment]
been trying a bunch, going to step back from this issue for a while since we are likely to work this as part of load testing.  Going to leave it open, unlikely to be closed as part of Tut1 MVP.

**Comment by dehann** [comment]
There were time out errors, so I was not able to just easily upload 1000 sessions and wait for solves.  More load testing work required in general, probably not specific to Tut1.

**Comment by jim-hill-r** [comment]
Time out errors? Like in the waitForCompletion step? I think any test like this should not include that. The goal is to queue 1000 and then come back later to look at them. Not wait for each one. This is a proper async situation.

Like I would queue up 1000, then waitForCompletion each one for like days haha and time how long it takes.

**Comment by jim-hill-r** [comment]
Also, drop a note in slack when you start a run like this, so I don't redeploy the code. We only have on env right now so if I redeploy it mid test it will destroy your test. That is maybe what happened.

**Comment by jim-hill-r** [comment]
I moved this to Cloud Preparedness. Can I remove from Tutorial 1?

**Comment by GearsAD** [comment]
Sounds good.

**Comment by GearsAD** [comment]
@dehann Slight improvements on the script to make it async:
```julia
using NavAbilitySDK
using Random
using LinearAlgebra

# Set the session count here.
ids = 1:10

apiUrl = "https://api.d1.navability.io"
userId = "Guest"
robotId = "MonteCarlo_10"
sessionId = "Session_"
client = NavAbilityHttpsClient(apiUrl)

contexts = [Client(userId,robotId,sessionId*string(i)) for i in ids]
solveIds = []
@time for i in ids
  context = contexts[i]
  @info "Running context $(i)"
  variables = [
    Variable("x0", :Pose2),
    Variable("x1", :Pose2),
    Variable("x2", :Pose2),
    Variable("x3", :Pose2),
    Variable("x4", :Pose2),
    Variable("l1", :Point2)
  ]
  factors = [
    Factor("x0f1", "PriorPose2", ["x0"], 
      PriorPose2Data(
        Z=FullNormal(
          [0.0, 0.0, 0.0], 
          diagm([0.05, 0.05, 0.01].^2)))),
    Factor("x0x1f1", "Pose2Pose2", ["x0","x1"], 
      Pose2Pose2Data(
        Z=FullNormal(
          [1.0, 0.0, pi/2], 
          diagm([0.1, 0.1, 0.01].^2)))),
    Factor("x1x2f1", "Pose2Pose2", ["x1","x2"], 
      Pose2Pose2Data(
        Z=FullNormal(
          [1.0, 0.0, pi/2], 
          diagm([0.1, 0.1, 0.01].^2)))),
    Factor("x2x3f1", "Pose2Pose2", ["x2","x3"], 
      Pose2Pose2Data(
        Z=FullNormal(
          [1.0, 0.0, pi/2], 
          diagm([0.1, 0.1, 0.01].^2)))),
    Factor("x3x4f1", "Pose2Pose2", ["x3","x4"], 
      Pose2Pose2Data(
        Z=FullNormal(
          [1.0, 0.0, pi/2], 
          diagm([0.1, 0.1, 0.01].^2)))),
                  
    Factor("x0l1f1", "Pose2Point2BearingRange", ["x0","l1"], 
      Pose2Point2BearingRangeData(
        bearing = Normal(0, 0.03), 
        range = Normal(0.5, 0.1))),
    Factor("x4l1f1", "Pose2Point2BearingRange", ["x4","l1"], 
      Pose2Point2BearingRangeData(
        bearing = Normal(0, 0.03), 
        range = Normal(0.5, 0.1)))
  ]

  # Add the variables
  @info "$(i): Pushing variables..."
  resultIds = String[]
  for v in variables
    push!(resultIds, addVariable(client, context, v))
  end
  # waitForCompletion(client, string.(resultIds); expectedStatuses=["Complete"])

  # Add the factors
  @info "$(i): Pushing factors..."
  resultIds = String[]
  for f in factors
    push!(resultIds, addFactor(client, context, f))
  end
  # waitForCompletion(client, string.(resultIds); expectedStatuses=["Complete"])

  # Solve the session
  @info "$(i): Solving session..."
  resultId = solveSession(client, context)
  push!(solveIds, resultId)
  # resultId = solveSession(client, context)
  # push!(solveIds, resultId)

  # sleep(60)
end

sessions = [c.sessionId for c in contexts]
@info "Solve IDs: $(solveIds)"
@info "Sessions: $(sessions)"

# Wait for all solves.
waitForCompletion(client, solveIds; maxSeconds=3600)

# Send requests to solve all sessions
solveIDs = []
for i in ids
  context = contexts[i]
  resultId = solveSession(client, context)
  push!(solveIds, resultId)
end

# Wait for all solves.
waitForCompletion(client, solveIds; maxSeconds=3600)

# Get the PPEs 
# variables = getVariables(client, context; detail=SUMMARY)
# ppes = Dict([v["label"] for v in variables].=>[v["ppes"] for v in variables])
```

**Comment by GearsAD** [comment]
You can easily push a thousand sessions in about 13 minutes.

**Comment by jim-hill-r** [comment]
Is that good? Wondering what would be good and what would be impressive.

**Comment by dehann** [comment]
Sam, Cool, thanks for upgrades to the script!

I think ability to push 1000 sessions in 5-10 mins is already impressive!!

These are small sessions.  Many of the problems in the naval / marine mapping world are around 500-2000 variables for large prolems -- i mean like map an entire ship hull from an underwater robot.  The mission time for something like that is around 2 hours.

Other cases, like a quad rotor drone capturing images for inspection, the number of variables and factors are around 10'000.  The mission time for a drone to collect this much data is likely two flights of 15mins each, so if the upload can complete live from the robot (that would need image or feature sets as well, so upload of maybe around 500-1000 variables per minute would be a good "Enterprise Performance".  Solving time is something else -- around 4-8 hours robust solve time seems like an acceptable delay.

Something like self driving map building of cities number in the ~10M.  Parametric solve is only thing that can do those in reasonable time right not (around 4 hours of solving for problem of around 20M variables).  A Robust solve within 72 hours will be okay, but then we'd need some sort of "Verifiable Certificate" or something to go along with that result (again Enterprise Level Feature).

Nonparametric solving time with multiproc / multithread on 32 cores for problem of around 10'000 should take around 60-90mins.

The Marine Appl example with its ultra aggressive memory hogging solve over 50 variables took about 15-20mins for a full batch solve of the 7 mins of robot data.  These are the new ScatterAlignPose2 factors which do a lot of internal computations.  I'd expect with speed upgrades the solving time to be cut in half or better.

**Comment by GearsAD** [comment]
@dehann Is this done?
