### ISSUE TITLE
Close out CJL Tutorial 1 Todos 

### ISSUE THREAD

**Issue by dehann** [NavAbility/BinderNotebooks#44]
We need this complete ASAP please.
- [x] https://github.com/JuliaRobotics/Caesar.jl/issues/817

**Comment by dehann** [comment]
Doing this properly will also need:
 - EDITED first comment above, https://github.com/JuliaRobotics/Caesar.jl/issues/817

**Comment by dehann** [comment]
- https://github.com/JuliaRobotics/Caesar.jl/pull/828

**Comment by Affie** [comment]
Link to manifolds page added https://github.com/NavAbility/BinderNotebooks/pull/45
