### ISSUE TITLE
Run through tutorial 1 notebooks and confirm they work in Binder

### ISSUE THREAD

**Issue by Affie** [NavAbility/BinderNotebooks#59]

**Comment by dehann** [comment]
HI @Affie , can you please confirm this for all three, now that SDKs have been tagged with necessary fixes/features:
- [x] CJL version
- [x] SDK.jl version
- [x] SDK.py version

**Comment by Affie** [comment]
With SDK.jl, looks related to running code too fast, a second time it went through without error.
- getting the PPEs can be too quick for solutions to exist in them.
- request did not complete in time.
![image](https://user-images.githubusercontent.com/6612981/161446072-18deeb42-4221-4d56-a1f9-6c8eaa689fdf.png)

Other than that no issues. 
I'm still going to read and run through when I'm fresh, I just ran everything now.

**Comment by dehann** [comment]
@Affie , could you perhaps lengthen the timeout for this first run location in the SDK binder notebooks for Tut1 please.  It should just be a keyword option on the `waitForCompletion` call.

**Comment by GearsAD** [comment]
Yep,

waitForCompletion(client, resultIds, expectedStatuses=["Complete"],
maxSeconds=180)
