### ISSUE TITLE
Someone overwrote previous fixes on CJL API Tut1

### ISSUE THREAD

**Issue by dehann** [NavAbility/BinderNotebooks#67]
I have to now go dig to find who dunnit, and I have to back out how far back the changes go.

**Comment by Affie** [comment]
What is it that changed?

**Comment by Affie** [comment]
I just went through the entire timeline of the caesar.jl tut 1 and didn't see anything strange.

**Comment by dehann** [comment]
I had a few commits that fixed things like `DFG.plotDFG(...)`, but that looks like it was reverted.  The code did not run.  I also had random grammar fixes, but dont have the time to go looking for them now again.  I'm just accepting some work was lost and we'll have to find those text fixes again.  I did get the code to run again by repeating the fixes.

PS, Requires.jl is actually not order sensitive, so can load conditional packages later and still get the functionality load on earlier packages.

**Comment by Affie** [comment]
> PS, Requires.jl is actually not order sensitive, so can load conditional packages later and still get the functionality load on earlier packages.

Ok, that changed, it used to require revise to load out of order. good to know.

**Comment by Affie** [comment]
It imported `DistributedFactorGraphs` from day 1, so `DFG.` was not needed until it was no longer imported by the latest pr.

**Comment by dehann** [comment]
No problem, not sure where what how, but would have taken longer to debug.  Notebooks are a little hard to check diffs for certain commits.  Luckily these are short notebooks.  Think I'm just going to merge often and keep the changes per PR concise and related.

On DFG vs the Import, I wasnt sure which way to go.  What won me over was, just import one package for the tutorials and be done.  I think there is a real premium on these Tutorials to make them as simple as possible.  

Thanks for checking!
