### ISSUE TITLE
Tut1 Team Acceptance (Last Issue to Close)

### ISSUE THREAD

**Issue by dehann** [NavAbility/BinderNotebooks#70]
This is an acknowledgement that this epic is complete. Not just your part or what you know, but you are confident that we can move forward and call this done from every perspective. 

The work is ready for showtime. It can be marketed and shown without hesitation.

- [x] Sam
- [x] Dehann
  - PR awaiting merge: https://github.com/NavAbility/cloud-system/pull/463
- [ ] Jim
- [x] Johan

**Comment by Affie** [comment]
I'll re-run tests in binder tomorrow.

**Comment by GearsAD** [comment]
I'm happy with tut1

**Comment by Affie** [comment]
If this is for end-to-end acceptance, there are still some issues to be closed.

If it's just the notebooks, I'm happy.

**Comment by jim-hill-r** [comment]
> If this is for end-to-end acceptance, there are still some issues to be closed.

This is for end-to-end.

**Comment by jim-hill-r** [comment]
The card and landing page text is complete and ready for review.

Are we going to move https://github.com/NavAbility/NavAbilitySDK.jl/issues/81 out of this epic? Is so, then I'll move it and do my review of the end to end.

**Comment by dehann** [comment]
yeah, lets move SDK.jl 81 out as that is a code quality thing more than MVP end-to-end functionality.  I'd say it's above and beyond, unless there is push back.

**Comment by GearsAD** [comment]
Yeah it's not tied to MVP, I'm going to move it out.

**Comment by dehann** [comment]
I just checked the Static Rendered pages and they still have the old content.  I think Jim just updated the image rendering there, so these will likely update with the nightly build?

**Comment by Affie** [comment]
Static rendering is not working on plotSLAM2D

**Comment by dehann** [comment]
- All static rendering to PNG has been fixed.
- Complete rewrite of intro with big application example lead in
- SDK.jl v0.4.1 allows for graphics markdown badge links to Graph and Geom Viz, updated in notebook.
  - SDK.py still uses url links for viz, will update that to badges as part later tutorial work
- I checked CJL, SDK.jl, SDK.py, 
- updated landing page, awaiting a review and merge:
  - https://github.com/NavAbility/cloud-system/pull/463

I have no further MVP updates on Tut1, @Affie and @jim-hill-r please do acceptance so we can close the epic -- thanks.

**Comment by GearsAD** [comment]
Can we close this, call it a success?

**Comment by dehann** [comment]
Slight scope creep that I'm going to fix today:
- ~~I'm going to add image outputs to all notebooks for the static renders to make sense.~~
- I'll make sure `guest@navability.io` is used on all notebooks for Tut1.

Bar that, I'm planning close the Tut1 Epic tonight regardless - it's the `#2` priority Roadmap Epic and has been blocked on the same single acceptance ticket for over 2 weeks now.  Assuming @jim-hill-r might review at some point, and if he finds stuff we can triage those issues separately.

**Comment by dehann** [comment]
I just checked, SDK.jl and SDK.py on Tut1 use `guest@navability.io` as userId
