### ISSUE TITLE
Too many users Binder

### ISSUE THREAD

**Issue by jim-hill-r** [NavAbility/BinderNotebooks#86]
Error loading NavAbility/BinderNotebooks/main! (Found built image, launching...
Too many users on this BinderHub! Try again soon.)

**Comment by jim-hill-r** [comment]
Inform Arvinder on Slack once resolved.

**Comment by dehann** [comment]
There is a separate issue tracking the increased resources request to Binder.  I sent to Arvinder (thank Jim for reminder)
